apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnet-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnet-app
  template:
    metadata:
      labels:
        app: aspnet-app
    spec:
      containers:
      - name: aspnet-app
        image: aspnetcore8:1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aspnet-service
spec:
  type: NodePort
  selector:
    app: aspnet-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30000  # El puerto en el nodo donde estara disponible el servicio
  
