apiVersion: apps/v1 
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: angular-app
  template:
    metadata:
      labels:
        app: angular-app
    spec:
      containers:
      - name: angular-app
        image: hub-de-entretenimiento_angularv16:1 
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: angular-app-service
spec:
  type: NodePort
  selector:
    app: angular-app
  ports:
    - protocol: TCP
      port: 80 # the port that the service is running on in the cluster
      targetPort: 80 # the port exposed by the service
      nodePort: 31000  # El puerto en el nodo donde estará disponible el servicio